---
- name: Install immich-cli
  package:
    name: immich-cli
    state: present

- name: Install postgresql
  package:
    name: postgresql@18
    state: present

- name: Install pwgen
  package:
    name: pwgen
    state: present

- name: Install tradingview
  community.general.homebrew_cask:
    name: tradingview
    state: present

- name: Install whatsapp
  community.general.homebrew_cask:
    name: whatsapp
    state: present