---
- name: Install Garmin Express
  community.general.homebrew_cask:
    name: garmin-express
    state: present

- name: Install immich-cli
  package:
    name: immich-cli
    state: present

- name: Install joplin
  community.general.homebrew_cask:
    name: joplin
    state: present

- name: Install postgresql
  package:
    name: postgresql@18
    state: present

- name: Install pwgen
  package:
    name: pwgen
    state: present

- name: Install tradingview
  community.general.homebrew_cask:
    name: tradingview
    state: present

- name: Install twingate
  community.general.homebrew_cask:
    name: twingate
    state: present

- name: Install whatsapp
  community.general.homebrew_cask:
    name: whatsapp
    state: present