---
- name: Install bitwarden
  community.general.homebrew_cask:
    name: bitwarden
    state: present

- name: Install docker
  community.general.homebrew_cask:
    name: docker
    state: present

- name: Install ffmpeg
  package:
    name: ffmpeg
    state: present

- name: Install homeassistant
  community.general.homebrew_cask:
    name: home-assistant
    state: present

- name: Install jellyfin
  community.general.homebrew_cask:
    name: jellyfin
    state: present

- name: Install nextcloud
  community.general.homebrew_cask:
    name: nextcloud
    state: present

- name: Install redis
  package:
    name: redis
    state: present