---
- name: Install ffmpeg
  package:
    name: ffmpeg
    state: present

- name: Install jellyfin
  community.general.homebrew_cask:
    name: jellyfin
    state: present

- name: Install navidrome
  package:
    name: navidrome
    state: present

- name: Install podman desktop
  community.general.homebrew_cask:
    name: podman-desktop
    state: present
